deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
https://github.com/IBM/ibm-cert-manager-operator/issues/14
=> Removed extra comma from alm example.

deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml, deploy/operator.yaml
The previous pull request only added the annotations to the operands. This PR adds it to the operator's deployment as well.
=> Add metering annotations to our operator

pkg/resources/constants.go
Enables all controllers except the ingress-shim one.
=> Added the controllers argument

deploy/access-role.yaml, deploy/access-rolebinding.yaml, deploy/crds/certificate-crd.yaml, deploy/crds/certificate_cr.yaml, deploy/crds/clusterissuer-crd.yaml, deploy/crds/clusterissuer_cr.yaml, deploy/crds/issuer-crd.yaml, deploy/crds/issuer_cr.yaml, deploy/crds/operator.ibm.com_certmanagers_crd.yaml, deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml, deploy/operator.yaml, deploy/role.yaml, deploy/role_binding.yaml, deploy/service_account.yaml
1. Added app.kubernetes.io labels on all the resources in deploy directory.
2. Added nodeAffinity in operator deployment
3. Added CPU and memory resource limits and requests in operator container
4. Added securityContext for operator container
=> Resolve cv-lint issues

build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x, deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml, deploy/operator.yaml, pkg/resources/constants.go
1. Set default value of disableHostNetwork to true
2. Operand version change in operator code (cert-manager to 0.10.4 and configmap-watcher to 3.3.2)
3. UBI image update for operator
4. Update CS productVersion from 3.3.0 to 3.4.0
=> Operator Updates

deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml, deploy/operator.yaml
Required for IBM Certification
=> Set host parameters to false in operator deployment

.osdk-scorecard.yaml, deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.6.2/certificate-crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.6.2/clusterissuer-crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.6.2/ibm-cert-manager-operator.v3.6.2.clusterserviceversion.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.6.2/issuer-crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.6.2/operator.ibm.com_certmanagers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml, deploy/operator.yaml, version/version.go
Fix for OOMKilled issue on Power
=> 3.6.2-Increasing operator memory limit

deploy/olm-catalog/ibm-cert-manager-operator/3.6.3/ibm-cert-manager-operator.v3.6.3.clusterserviceversion.yaml, deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
- Update operator image to reference SHA digest.
- Move 3.6.3 to beta
=> 3.6.3 Beta changes as a part of CS 3.4 Fix3

.osdk-scorecard.yaml, Makefile, build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x, deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/certificate-crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/clusterissuer-crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/ibm-cert-manager-operator.v3.9.0.clusterserviceversion.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/issuer-crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/operator.ibm.com_certmanagers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml, deploy/operator.yaml, pkg/resources/constants.go, version/version.go
- UBI image update
- Update of node affinity labels
- Adding 3.9.0 CSV
- Stable v3 channel updates
- Operand SHA references update
=> Cert Manager Operator Q1 updates

deploy/crds/certificate_cr.yaml, deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
- Add duration/renewbefore in certificate CR
-  remove it from certmanager operator CR
=> Add duration/renewbefore in certificate CR

.osdk-scorecard.yaml, Makefile, build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x, deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.8.2/certificate-crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.8.2/clusterissuer-crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.8.2/ibm-cert-manager-operator.v3.8.2.clusterserviceversion.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.8.2/issuer-crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.8.2/operator.ibm.com_certmanagers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml, deploy/operator.yaml, pkg/controller/certmanager/deploys.go, pkg/resources/constants.go, pkg/resources/util.go, version/version.go
- Bump up the CSV to 3.8.2
- update node anti-affinity
- update manifest tool version
- update UBI image digest
- auto-update operand image update
=> 3.8.2 eus stream changes

build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x, deploy/olm-catalog/ibm-cert-manager-operator/3.8.2/ibm-cert-manager-operator.v3.8.2.clusterserviceversion.yaml, deploy/operator.yaml
update ubi version to latest 8.3-298
update tags
=> eus operator ubi updates

build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x, deploy/olm-catalog/ibm-cert-manager-operator/3.10.0/ibm-cert-manager-operator.v3.10.0.clusterserviceversion.yaml, deploy/operator.yaml
ubi updates
update ubi to latest - 8.3-298
update configmapwatcher tag
=> ubi updates

Makefile, OWNERS, common/scripts/replace-dev-images.sh, deploy/olm-catalog/ibm-cert-manager-operator/3.10.0/ibm-cert-manager-operator.v3.10.0.clusterserviceversion.yaml
new indentation in CSV file does not affect anything, already tested.
=> added new quality of life commands to test changes quickly

build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x
ubi updates for ubi automation
update ubi to latest ubi8 minimal prior to automation
=> ubi updates for automation

deploy/olm-catalog/ibm-cert-manager-operator/3.11.0/ibm-cert-manager-operator.v3.11.0.clusterserviceversion.yaml
=> changed containerImage in CSV to use latest for consistency with spec

Makefile, deploy/olm-catalog/ibm-cert-manager-operator/3.12.0/ibm-cert-manager-operator.v3.12.0.clusterserviceversion.yaml, pkg/resources/constants.go, pkg/resources/containers.go
Configured the probes so that they are not run as often since it is unnecessary; the operands are robust enough to recover from error by themselves.
Increased the number of failures before k8s decides to restart the pod to deal with CPU throttling
=> updated liveness and readiness probes' configurations

deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml, deploy/role.yaml, pkg/controller/certificate/certificate_controller.go, pkg/controller/certmanager/prereqs.go, pkg/controller/issuer/issuer_controller.go, pkg/resources/pods.go, pkg/resources/rbac.go
RBAC changes based on https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/cainjector-rbac.yaml
=> updated code to deploy cainjector successfully

cmd/manager/main.go, deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
It has the same configuration as common-service operator
=> add liveness and readiness probes

SECURITY_CONTACTS, deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/acme.cert-manager.io_challenges_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/acme.cert-manager.io_orders_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_certificaterequests_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/cert-manager.io_clusterissuers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/operator.ibm.com_certmanagers_crd.yaml, deploy/role.yaml, pkg/controller/certmanager/deploys.go, pkg/controller/certmanager/prereqs.go, pkg/resources/constants.go, pkg/resources/containers.go, pkg/resources/pods.go, pkg/resources/rbac.go, pkg/resources/util.go
Update RBAC according to [upstream](https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/rbac.yaml)
Update startup options according to [upstream](https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/deployment.yaml)
=> Update cert manager controller to v1.5

Makefile, build/Dockerfile, build/Dockerfile.ppc64le, build/Dockerfile.s390x, common/config/.hadolint.yml, common/scripts/config_docker.sh
* opt-in of ubi base image automated builds
* config docker when building images
* fix base image file name
=> opt-in of ubi base image automated builds (#142)

.osdk-scorecard.yaml, deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/acme.cert-manager.io_challenges_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/acme.cert-manager.io_orders_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_certificaterequests_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_certificates_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_clusterissuers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/cert-manager.io_issuers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_certificaterequests_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_certificates_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_challenges_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_clusterissuers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_issuers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/certmanager.k8s.io_orders_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/ibm-cert-manager-operator.v4.0.0.clusterserviceversion.yaml, deploy/olm-catalog/ibm-cert-manager-operator/4.0.0/operator.ibm.com_certmanagers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml, version/version.go
operator version: 4.0.0
operand version: 1.0.0-jetstack.1.5.1
=> bump version to 4.0.0 for future branch

.osdk-scorecard.yaml, common/scripts/bump_up_csv.sh, deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/acme.cert-manager.io_challenges_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/acme.cert-manager.io_orders_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/cert-manager.io_certificaterequests_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/cert-manager.io_certificates_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/cert-manager.io_clusterissuers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/cert-manager.io_issuers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_certificaterequests_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_certificates_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_challenges_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_clusterissuers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_issuers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/certmanager.k8s.io_orders_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/ibm-cert-manager-operator.v3.16.0.clusterserviceversion.yaml, deploy/olm-catalog/ibm-cert-manager-operator/3.16.0/operator.ibm.com_certmanagers_crd.yaml, deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml, version/version.go
changed bump-csv script to leave `containerImage` field unchanged in CSV since the tag has to match image tag
=> updated version to 3.16.0

config/rbac/role.yaml, controllers/operator/certmanager_controller.go, controllers/operator/prereqs.go
accidentally removed after operator-sdk changes
=> added back RHACM permissions

apis/certmanager/v1alpha1/certificate_types.go, apis/certmanager/v1alpha1/certificaterequest_types.go, apis/certmanager/v1alpha1/challenge_types.go, apis/certmanager/v1alpha1/issuer_types.go, apis/certmanager/v1alpha1/order_types.go, bundle/manifests/certmanager.k8s.io_certificaterequests.yaml, bundle/manifests/certmanager.k8s.io_certificates.yaml, bundle/manifests/certmanager.k8s.io_challenges.yaml, bundle/manifests/certmanager.k8s.io_issuers.yaml, bundle/manifests/certmanager.k8s.io_orders.yaml, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/crd/bases/certmanager.k8s.io_certificaterequests.yaml, config/crd/bases/certmanager.k8s.io_certificates.yaml, config/crd/bases/certmanager.k8s.io_challenges.yaml, config/crd/bases/certmanager.k8s.io_issuers.yaml, config/crd/bases/certmanager.k8s.io_orders.yaml
RHACM permissions added back to bundle
=> changed v1alpha1 CRDs back to non subresource status

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/operator/certmanager_controller.go, controllers/resources/rbac.go
because of upstream change https://github.com/cert-manager/cert-manager/pull/4638
=> fix missing patch permission for controller pod

Makefile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml, config/samples/operator_v1alpha1_certmanager.yaml, controllers/resources/constants.go
Migrate image registry from quay.io to ICR
=> migrate to ICR

controllers/certmanager/certificate_controller.go
because cannot simply compare v1alpha1 spec with v1 spec since they are
different. Need to convert the v1alpha1 spec to v1 first and then
compare it to the existing v1 Certificate
This reverts commit 561f692227405ff75c2d603e4e32777acd8d5bdf.
=> Revert "fixed v1 certificate not updating when v1alpha1 updated (#252)"

controllers/cert-manager/podrefresh_controller.go
because the functions to search for workloads mounting certificate
secret was searching across all namespaces, so changed to check only in
the namespace of the Certificate which triggered the reconcile.
A bug from searching all namespaces is when there are two certificates
with the same name in different namespaces, and there are two workloads,
again, one in each namespace with a certificate of the same name. When
one of the Certificates get renewed, both workloads will be restarted
even though one is in a different namespace from the certificate being
renewed.
Signed-off-by: Henry Li <henry.h.li@ibm.com>
=> added list options to podrefresh logic

Makefile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Update to go along with psirt changes for cert manager
=> bump version for 3.19.3

Makefile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
=> bump version to 3.21.4

CONTRIBUTING.md, Makefile, README.md, apis/operator/v1alpha1/certmanager_types.go, bundle.Dockerfile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, bundle/manifests/operator.ibm.com_certmanagers.yaml, bundle/metadata/annotations.yaml, common/Makefile.common.mk, common/config/mdl.rb, config/crd/bases/operator.ibm.com_certmanagers.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
The CSV has a lot of changes, but it's 99% indentation changes because of how yq formats things
=> version bump and doc change

Makefile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
=> bump ltsr verison to 3.21.5

README.md
Signed-off-by: Henry Li <henry.h.li@ibm.com>
=> no-op PR to trigger PROW build for new images

controllers/cert-manager/certificaterefresh_controller.go
=> leaf refresh enhancement

controllers/certmanager/certificate_controller.go, controllers/certmanager/issuer_controller.go, controllers/operator/certmanager_controller.go
=> hide RHACM error message

Makefile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
=> bump version for 3.19.7

common/Makefile.common.mk
Signed-off-by: Xinchun Liu <xcliu@ca.ibm.com>
=> update prow change into ltsr

Makefile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Signed-off-by: Henry Li <henry.h.li@ibm.com>
=> bumped version to 4.0.0

Makefile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
=> bump up version to 3.25 for cs3.23

controllers/operator/certmanager_controller.go
=> remove finalizer

Makefile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
=> bump version for 3.19.8

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Merge in these changes after community code sync changes merged in operand repo
=> update cert manager image versions

controllers/operator/certmanager_controller.go
=> remove finalizer in ltsr

Dockerfile, Dockerfile.orig, Dockerfile.ppc64le, Dockerfile.s390x, Makefile, common/config/.hadolint.yml, common/scripts/config_docker.sh
=> new artifactory image endpoint (cert manager)

Dockerfile, Dockerfile.orig, Dockerfile.ppc64le, Dockerfile.s390x, Makefile, common/config/.hadolint.yml, common/scripts/config_docker.sh
=> [ltsr] new artifactory image endpoint (cert manager)

Dockerfile, Dockerfile.orig, Dockerfile.ppc64le, Dockerfile.s390x, Makefile, common/config/.hadolint.yml, common/scripts/config_docker.sh
=> [future] new artifactory image endpoint (cert manager)

Makefile, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
Signed-off-by: YuChen <yuchen.shen@mail.utoronto.ca>
=> bump to v3.25.1 for v3.23.1

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml, controllers/resources/constants.go, controllers/resources/util.go
Add suggest namespace and deploy the operand in the same namespace with operator
=> Add suggest namespace

controllers/operator/deploys.go, controllers/resources/certmanager.go
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58030
Same as https://github.com/IBM/ibm-cert-manager-operator/pull/329, this is for CP3.0,
=> convert resource.quantity to string

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58764
=> [CM LTSR] "disconnected" annotation for certification assessment

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml
fix for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58680#issuecomment-57982637
=> [LTSR] Update ImagePullPolicy to IfNotPresent

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58763
=> [Bedrock 4.1 CM] "disconnected" annotation for certification assessment 

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml
fix for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58680#issuecomment-57982637
=> [Bedrock 4.1 CM] Update ImagePullPolicy to IfNotPresent

go.mod, go.sum
bump jwt package one z version for security reasons
=> update jwt to 4.4.3

controllers/operator/certmanager_controller.go
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59421
=> update cr version

controllers/operator/deploys.go, controllers/resources/containers.go
expose ephemeral storage limit to certmanagerconfig cr
also change `readonlyrootfilesystem` value to true in cert manager webhook container
=> Ephemeral storage limit

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
After sync with community, update version to reflect new changes. The CRDs are already matching the community level so no changes there.
=> update version to 1.11.12-jetstack.1.13.2 for community code sync

controllers/operator/deploys.go, controllers/resources/containers.go
for ephemeral storage setting: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59738
=> Webhook set readOnlyRootFileSystem to true

controllers/operator/deploys.go, controllers/resources/containers.go
set readOnlyRootFileSystem in cert-manager-webhook pod to true
=> [ltsr] webhook readOnlyRootFileSystem to true

Dockerfile, Dockerfile.ppc64le, Dockerfile.s390x, go.mod, go.sum
=> updated base image to ubi9

apis/operator/v1/certmanagerconfig_types.go, bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml, bundle/manifests/operator.ibm.com_certmanagerconfigs.yaml, config/crd/bases/operator.ibm.com_certmanagerconfigs.yaml, controllers/operator/deploys.go
How to test
1. make `push-image-amd64 && make bundle-run`
2. edit operator's deployment image on cluster to the image built in step 1
3. update the CertManagerConfig CR named `default` by adding `enableInstanaMetricCollection: true` to spec
4. verify that operand deployments have the updated environment variable
=> added instana configuration
