deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v2.0.0.clusterserviceversion.yaml
deploy/role.yaml
design-spec.md
pkg/controller/certmanager/certmanager_controller.go

The CR instance must be named "default"
So any CR instance not named "default" will get this status to notify them they're not allowed to be created:
````
Name:         example-certmanager
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  operator.ibm.com/v1alpha1
Kind:         CertManager
Metadata:
Creation Timestamp:  2020-02-13T17:42:19Z
Generation:          1
Resource Version:    15342
Self Link:           /apis/operator.ibm.com/v1alpha1/certmanagers/example-certmanager
UID:                 2ee29d7a-4e88-11ea-969d-00000a1507b9
Spec:
Enable Webhook:  true
Image Registry:  hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64
Pull Secret:
Name:  pull-secret-2
Events:
Type     Reason       Age    From                       Message
----     ------ …
```

Allow only one CR instance to pass through

---

.osdk-scorecard.yaml
deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v2.0.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/certmanager/prereqs.go
pkg/resources/constants.go
pkg/resources/pods.go

The CSV files needed to be update for both the issue below and with the missing information needed for pushing to quay.io/application.
We're removing the image pull secret since the images for both the operator and the operand will be in a public repository or (in the event of an offline install) will be in the OCP registry and should be public.
https://github.com/IBM/ibm-cert-manager-operator/issues/9

Update CSV files & remove image pull secret

---

deploy/role.yaml
deploy/role_binding.yaml
pkg/controller/certmanager/prereqs.go
pkg/resources/constants.go

Since we deploy in the `ibm-cert-manager-operator` namespace according to what we wrote in the [onboarding to meta-operator PR](https://github.com/IBM/meta-operator/pull/69/files), we need to fix the namespace referenced in the clusterrolebinding for the service account which will now be in the `ibm-cert-manager-operator` namespace. 
Also adding additional permission to namespaces in our role and returning any errors when we check for namespaces that are not a NotFound error.

Fixed the namespace of the service account in the clusterrolebinding

---

pkg/controller/certmanager/deploys.go
pkg/controller/certmanager/prereqs.go

Previously if the operator found other deployments of cert-manager (without the same name/namespace) it would deterministically delete it. Now, the logic is to show a warning that one already exists and suggests to remove it before we are able to deploy our own.

Update deployment logic

---

pkg/controller/certmanager/certmanager_controller.go
pkg/controller/certmanager/prereqs.go
pkg/resources/constants.go
pkg/resources/containers.go
pkg/resources/pods.go

Owning the cert-manager namespace so it's removed when the CR of CertManager is removed.
Also removed runAsUser since the range kept changing 
````
Warning  FailedCreate  7s (x13 over 28s)  replicaset-controller  Error creating: pods "cert-manager-controller-bbfb69bb5-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000550001: must be in the ranges: [1000570000, 1000579999] spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000550001: must be in the ranges: [1000570000, 1000579999]]
````

Added ownership to the namespace and removed runAsUser.

---

deploy/clusterrole.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
pkg/resources/containers.go
pkg/resources/rbac.go
pkg/resources/webhook_resources.go

We removed runAsUser and the webhook relied on the specific user to write to this directory. 
````
F0225 20:20:24.465329       1 cmd.go:42] open /home/webhook/tmp/client-ca-file035449862: permission denied
````
So we're removing the directory location to fix this error.

Remove tmpdir environment variable since we're running as any user.

---

common/config/.golangci.yml
go.sum
pkg/controller/certmanager/certmanager_controller.go
pkg/controller/certmanager/deploys.go
pkg/controller/certmanager/prereqs-webhook.go
pkg/controller/certmanager/prereqs.go
pkg/resources/constants.go
pkg/resources/deployments.go
pkg/resources/rbac.go
pkg/resources/webhook_resources.go

Due to the inability to remove our CR (cluster-scoped) by removing a subscription/csv (namespace-scoped), our resources are unable to be cleaned up when we're uninstalled by the ODLM. 
This places all the resource cert-manager-operator creates (deploys, service accounts, etc.) into the same namespace that the cert-manager-operator is deployed in to make it easy for ODLM to clean up the resources.

Deploy all cert-manager resources in the same namespace that the operator is deployed in

---

docs/adoption-guide.md
docs/design-spec.md

Design doc:
- added the logic for if an instance of cert-manager exists
- removed the part about image pull secrets
Adoption guide:
- Updated guide based on recent discussion

Update design doc and adoption guide doc

---

pkg/controller/certmanager/deploys.go
pkg/resources/constants.go

Previously did not account for having a forward slash when `imageRegistry` is specified. This logic takes care of it by removing it (no matter how many there are) to standardize the imageRegistry variable.

Fix logic handling image registry

---

build/Dockerfile
build/Dockerfile.ppc64le
build/Dockerfile.s390x

Docker inspect output:
````
$ DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect registry.access.redhat.com/ubi8/ubi-minimal:8.1-398
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:47e2f82dbede8ff990e6e240f82d78830e7558f7b30df7bd8c0693992018b1e3",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": "sha256:0c90c5b1901dc47d35ff28fc142735c02526e8f8c12a9b7d2ab6205021de3558",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 737,
"digest": …
```

Update the ubi base image to be based on the sha instead of the version.

---

pkg/resources/constants.go

The latest version is `3.3.1` https://github.ibm.com/IBMPrivateCloud/configmap-watcher/blob/master/RELEASE_VERSION

Use the correct configmap watcher version.

---

pkg/controller/certmanager/deploys.go

When a deployment is updated with additional labels, such as when the configmap-watcher restarts its pods, the operator will not accept the additional labels and immediately remove the update deployment. 
This PR changes the logic to check to see if the labels the deployment should have is a subset of the ones the deployment actually has. In other words, the labels of the deployment must minimally contain the labels it expects.

Prevent removing additional deployment labels

---

Makefile
common/config/.golangci.yml
deploy/crds/operator.ibm.com_certmanagers_crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/operator.ibm.com_certmanagers_crd.yaml
pkg/apis/operator/v1alpha1/certmanager_types.go
pkg/controller/certmanager/deploys.go

In OCP 3.11 the webhook can't be deployed using hostNetwork because the apiserver will fail to contact it. This mitigates the issue by setting it to false when it's ocp 3.11. The CertManager CRD now looks like this:
````
- apiVersion: operator.ibm.com/v1alpha1
kind: CertManager
metadata:
name: default
spec:
enableWebhook: true
imageRegistry: registry.mixhub.cn/integration/
ocp311: true
````
The hostNetwork is needed for OCP 4.x to be discovered by the apiserver.

Added additional field to determine if it's ocp 3.11

---

deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml

From testing a default install (no customizations). The operand images are located in this repo.

Add the exact repo to pull from in the default example CR.

---

deploy/crds/operator.ibm.com_certmanagers_crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v3.5.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/operator.ibm.com_certmanagers_crd.yaml
pkg/apis/operator/v1alpha1/certmanager_types.go
pkg/controller/certmanager/deploys.go

Renaming `ocp311` field to `disableHostNetwork`. 
This is because the webhook issue related to hostNetwork exists not just for OCP 3.11 but also for 4.4.
Solved Webhook error:
```
kubectl api-resources
error: unable to retrieve the complete list of server APIs: webhook.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
```

Renaming field ocp311 to disableHostNetwork

---

Makefile
deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/certificate-crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/clusterissuer-crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/issuer-crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/operator.ibm.com_certmanagers_crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
deploy/operator.yaml
version/version.go

1. Generated CSV for 3.6.0
2. Updated CSV manually with necessary fields after comparing it with 3.5.0
3. Makefile: Added install and uninstall targets to test the CSV locally through the command line
4. Tested the changes locally on test cluster by deploying the 3.6.0 CSV

Generate CSV for 3.6.0 release

---

deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.6.0/ibm-cert-manager-operator.v3.6.0.clusterserviceversion.yaml

Updated the certManagerStatus field in the CertManager CR to `''` from `{}` as it is of type string.

Fix certManagerStatus initialization in certmanager CR

---

build/Dockerfile
build/Dockerfile.ppc64le
build/Dockerfile.s390x
deploy/olm-catalog/ibm-cert-manager-operator/3.6.3/ibm-cert-manager-operator.v3.6.3.clusterserviceversion.yaml
deploy/operator.yaml

- Update UBI images to remove scan vulnerabilities
- Update operand SHA references to refer the latest operand images in quay
- Deployed in test cluster successfully

Update UBI images and operand SHA references

---

.osdk-scorecard.yaml
Makefile
common/scripts/config_docker.sh
common/scripts/get_image_sha_digest.sh
deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/certificate-crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/clusterissuer-crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/ibm-cert-manager-operator.v3.7.0.clusterserviceversion.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/issuer-crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/operator.ibm.com_certmanagers_crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
deploy/operator.yaml
pkg/resources/constants.go
version/version.go

- Update all operator version references to 3.7.0
- Update dev channel to 3.7.0 in package.yaml
- Update operand versions to 0.10.6 and 3.3.3 (configmap-watcher)
- Add new CSV 3.7.0
- CICD changes as per guidelines to push operator image to artifactory instead of quay

Update operator version to 3.7.0 and CICD changes

---

deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/ibm-cert-manager-operator.v3.7.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/resources/constants.go

As required by metering/licensing squad, removing productVersion annotation from the operator and operands altogether

Remove product version metering annotation

---

common/scripts/get_image_sha_digest.sh
deploy/olm-catalog/ibm-cert-manager-operator/3.7.0/ibm-cert-manager-operator.v3.7.0.clusterserviceversion.yaml
go.mod

- Update operand image SHA digest script to pull from artifactory and update CSV instead of operator.yaml
- Update operand SHA references
- Update go.mod to reflect go version 1.14

update go version to 1.14 and update operand shas

---

.osdk-scorecard.yaml
Makefile
common/scripts/bump_up_csv.sh
deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.1/certificate-crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.1/clusterissuer-crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.1/ibm-cert-manager-operator.v3.7.1.clusterserviceversion.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.1/issuer-crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.7.1/operator.ibm.com_certmanagers_crd.yaml
deploy/olm-catalog/ibm-cert-manager-operator/ibm-cert-manager-operator.package.yaml
version/version.go

- Bump up CSV from 3.7.0 to 3.7.1
- Add labels in 3.7.1 CSV to support multiple architectures
- Add automated script to bump up CSVs
- Point dev channel to 3.7.1 and beta to 3.7.0

3.7.1 CSV updates and multi-arch support

---

deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml
deploy/olm-catalog/ibm-cert-manager-operator/3.9.0/ibm-cert-manager-operator.v3.9.0.clusterserviceversion.yaml
pkg/controller/certificaterefresh/certificaterefresh_controller.go
pkg/resources/constants.go

Update the duration of root CA to 2 years
Replace hard coded namespace `ibm-common-services` with the deploy namespace

Update duration of root CA to 2 years

---

Makefile

v1.0.0 has a bug that causes it to improperly push the manifest when interacting with Artifactory.

update manifest-tool version to v1.0.3

---

cmd/manager/main.go
pkg/controller/certificaterefresh/certificaterefresh_controller.go
pkg/resources/constants.go

refresh logic now builds the default list of certificates whenever certificates are being refreshed. This default list is based on the certificates Common Services requires to function properly. Uses ODLM deployments as a guide to find where each instance of Common Services is deployed. This logic should also work for on-prem, singleton CS deployment

changed refresh leaf certificate logic to work with SaaS

---

.gitignore
Makefile
cmd/manager/main.go
deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
pkg/controller/certificate/certificate_controller.go

temporarily remove unnecessary versions from CRDs (v1alpha2, v1beta1, etc.) because operator-sdk generates a configmap too large for Kubernetes
update branch with master changes

fixed run-csv configmap error

---

deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
deploy/role.yaml
pkg/controller/certificate/certificate_controller.go
pkg/controller/issuer/issuer_controller.go

Issue: We can't inherit owner references from v1alpha1 cert-manager objects because we don't have the relevant permission to the parent resources of v1alpha1 cert-manager objects.
Error message:
```
forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on
```
This PR implements:
Set v0.10 cert manager CRs as the owner of v1.x cert manager CRs
Enable update logic: When v0.10 cert manager CRs are updated, v1.x cert manager CRs will be updated as well
Need to consider:
Should we watch the change of v1.x cert manager CRs and trigger the reconciliation for its owner?

feat: Set v1alpha1 objects as the owner of v1 objects

---

cmd/manager/main.go
deploy/olm-catalog/ibm-cert-manager-operator/3.13.0/ibm-cert-manager-operator.v3.13.0.clusterserviceversion.yaml
pkg/controller/add_podrefresh.go
pkg/controller/certificaterefresh/certificaterefresh_controller.go
pkg/controller/podrefresh/podrefresh_controller.go

1. Add pod refresh logic to the operator
2. Update certificates refresh controller to watch v1 certificate
3. Increase resources limit because watching secret.
**Limitations:**
1. Pods are restarted too many times. **Fix:** We can restart pods only when secrets are updated or only watch certificates spec change.
2. Watching secrets will make operator resources usage according to the number of secrets. **Fix:** Customize cache to avoid caching secrets.
3. Certificates refresh controller doesn't work with cluster issuer. **Fix:** Add cluster issuer type into operator api.

add pod refresh controller

---

pkg/controller/certmanager/prereqs.go

After removing hard coded namespace in the RBAC resources (roles and rolebindings), the functions to create the resources were not updated. The GET request to check if the resources existed was still trying to reference the hard coded namespace, which no longer existed.

fixed RBAC creation issue

---

pkg/controller/certificate/certificate_controller.go
pkg/controller/certificaterefresh/certificaterefresh_controller.go

Two scenarios covered:
1. After upgrade, v1alpha1 Certificates will eventually be converted to v1, but there is no guarantee that CA is converted before leaf certificates.
2. Some services could decide to implement v1 Certificates before others, so it is possible that a v1 CA is created while some services are still creating v1alpha1 leaf certificates.
How scenarios are addressed:
1. Conversion controller will automatically convert v1alpha1 leaf Certificates when a v1alpha1 CA Certificate is converted
- make it seem like v1alpha1 leaf is expired by deleting the secret
- update the v1alpha1 leaf so that a request is sent to conversion controller
2. Assuming v1alpha1 of the CA was not deleted by the service, then make it seem as though the v1alpha1 CA needs to be converted
- empty the …

convert leaf certificates when CA is updated

---

pkg/controller/certificate/certificate_controller.go
pkg/controller/certmanager/certmanager_controller.go
pkg/controller/certmanager/prereqs.go
pkg/controller/issuer/issuer_controller.go

Please let me know whether it is the correct behavior we want to coordinate with RHACM.
In the EUS version, we keep the ability of refreshing certificate for cert-manager-operator. So we should do the same thing in the latest version.
Reconcile certificate and issuer is the new function added in CS 3.12, and it should be disabled when RHACM 2.2 exists, right?

disable certificate and issuer reconciliation to support RHACM 2.2

---

pkg/controller/certificaterefresh/certificaterefresh_controller.go

simplified leaf cert refresh logic when using refresh label
fixed existing issue where only the leaf certificates from the last CA issuer the operator found were refreshed
refactored findLeafSecrets function to only find secrets and extracted out certificate listing logic into its own function

refresh v1alpha1 leaf certs

---

pkg/controller/podrefresh/podrefresh_controller.go

added predicate to filter out all events except for updates to Certificates which signify renewal
removed use of expirationLabel and instead rely on lastTransitionTime and restartLabel. The transitionTime represents when Certificate status was last updated, which should only be done by the cert-manager-controller and when it does, it means certificate secret is being updated. So if restartLabel time is after transitionTime, then that means pod was updated after the secret was updated, and this should work for multiple certificate secrets

fixed pod restart incorrectly restarting pods

---

controllers/operator/deploys.go
controllers/resources/containers.go

jetstack cert-manager changed the default leader election namespace of cainjector to `kube-system`, so we need to adjust it based on where we deploy cainjector, https://github.com/cert-manager/cert-manager/pull/4359/files#diff-8f19c736bead867fae4a4443ea0e7163ed04dad43c9523b0cd7773c759155074R25

set leader election namespace for cainjector

---

controllers/operator/deploys.go

The type of cpu and memory is `resource.Quantity` which is hard to compare, so this pr will convert it to DecimalSI and then convert this DecimalSI to string
For ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58030

 compare resource.Quantity type

---

controllers/cert-manager/podrefresh_controller.go

For ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57070
If two certificates are mounted by one pod, and those two certificates are refreshed in the same minute, The second certificate restart will not trigger a pod restart because the time labels are the same.
Test looks good to me:
```
labels:
app: auth-idp
app.kubernetes.io/instance: auth-idp
certmanager.k8s.io/time-restarted: 2023-6-5.184816
```
But it could cause some pods to restart multiple times in seconds if I delete cs-ca-certificate, not sure if that will cause any other errors
This image can be used to verify `quay.io/yuchen_li1/ibm-cert-manager-operator-amd64@sha256:607fd21dbc090ac598315d3d89f5af731780bff322d6576b66261565f375cb91`
How to test:  
1. install common-service
2. install ibm-cert-manager with other …

[LTSR] Make podrestart label more accurate

---

apis/operator/v1/certmanagerconfig_types.go
apis/operator/v1/zz_generated.deepcopy.go
config/crd/bases/operator.ibm.com_certmanagerconfigs.yaml
controllers/operator/certmanager_controller.go
controllers/operator/deploys.go
controllers/operator/util.go
controllers/resources/constants.go
controllers/resources/deployments.go

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60509
add a new field `.spec.labels` in certmanagerconfig CRD, ibm-cert-manager-operator will use these labels in this field to update its cr, deployments and pods

Service labelling

---

Makefile
bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
config/samples/operator_v1_certmanagerconfig.yaml
controllers/resources/certmanager.go

We will keep cert-manager version as 4.2.2 for Release 4.4
Slack discussion: https://ibm-cloudplatform.slack.com/archives/G9KFCQNL8/p1705418421937499

move cert-manager version down to 4.2.2

---

test-cert-chain.yaml

increase cert-rotation time in testcases to 10 mins, for some slow responsed cluster.

increase testcase cert-rotation time

---

PROJECT
apis/acme.cert-manager/v1/types_issuer.go
apis/acme.cert-manager/v1/zz_generated.deepcopy.go
apis/cert-manager/v1/certificate_types.go
apis/cert-manager/v1/issuer_types.go
apis/cert-manager/v1/zz_generated.deepcopy.go
controllers/operator/certmanager_controller.go
controllers/operator/deploys.go
controllers/operator/prereqs-webhook.go
controllers/operator/prereqs.go
controllers/operator/suite_test.go
go.mod
main.go

https://go.dev/ref/mod#major-version-suffixes
Starting with major version 2, module paths must have a major version suffix like /v2 that matches the major version. For example, if a module has the path example.com/mod at v1.0.0, it must have the path example.com/mod/v2 at version v2.0.0.

update go module to match major release v4

---

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml
controllers/resources/containers.go
controllers/resources/pods.go

**What this PR does / why we need it**:
add securityContext .ceccompProfile field to pod container
**Which issue(s) this PR fixes**:
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64465

add securityContext .seccompProfile field

---

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml

Adding OLM required metadataas defined in https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#con-operator-requirements_openshift-sw-cert-policy-products-managed and required by RH Certification
What this PR does / why we need it:
OLM has introduced several required annotations which operator bundle is missing.

Adding OLM required metadata

---

bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml

To comply with [`restricted` PodSecurityAdmission](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) this PR sets `runAsNonRoot: true` in the controller Deployment security context.

fix: set runAsNonRoot: true in controller deploy

---

helm-cluster-scoped/templates/cluster-rbac.yaml
helm-cluster-scoped/values.yaml
helm/templates/deployment.yaml
helm/templates/rbac.yaml
helm/values.yaml

Updated operatorNamespace value to certmgrNamespace between the helm and helm-cluster-scoped folders. Follows consistency with cert-manager having its own namespace and avoiding conflict naming variables between other charts.

Updated operatorNamespace value to certmgrNamespace

---

Makefile
bundle/manifests/ibm-cert-manager-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/manifests/bases/ibm-cert-manager-operator.clusterserviceversion.yaml
config/samples/operator_v1_certmanagerconfig.yaml
controllers/resources/certmanager.go
helm-cluster-scoped/Chart.yaml
helm/Chart.yaml
helm/templates/deployment.yaml

**What this PR does / why we need it:**
Update CM to 4.2.19 for CS 4.6.19

Bump cert-manager version to 4.2.19
